### PR TITLE
Add Group field reordering using the react-draggable-list component

### PR DESCRIPTION
**Pull request by etx**
Group field reordering with the react-draggable-list component.

screen shot 2018-01-10 at 2 03 37 pm

### CODE REVIEW

**Comment by JasonEtco** [comment]
😍 this is looking great. I've pulled it down and tried it out, working well. I've made some changes to this branch locally but it won't let me push my changes to this PR; I believe you have to check "Allow edits from maintainers" (see this [help doc article](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/)). They're mostly code-style changes with some occasional code cleanup, linting, etc.

**Comment by JasonEtco** [comment]
Actually, I take that back; it looks like setting some values then rearranging the tiles clears all the values.

**Comment by etx** [comment]
That allow edits check box is already ticked in the PR. You should be good on that.

It's clearing the values? I thought I tested it pretty well, didn't see that but I'll look again.

**Comment by JasonEtco** [comment]
@etx no console errors; I tried it with a group containing two text fields. I added two, filled them in (without saving) and moved em around. The values cleared when I dropped them.

> That allow edits check box is already ticked in the PR. You should be good on that.

Hm I must have done something wrong

**Comment by JasonEtco** [comment]
Alrighty @etx I pushed my changes. Let me know if something seems off to you there.

**Pull request closed without merging**
