### PR TITLE
Group field reordering and default server templates

### PR DESCRIPTION
**Pull request by etx**
Here are a couple features I wanted / needed. The template error is quite useful and the reordering of the group field is really needed. I'm no React ninja so it may need some fit and finish. 

🤘🤘

### CODE REVIEW

**Comment by JasonEtco** [comment]
😮 You've done so much, this is so awesome! 😍

I'm looking forward to giving your changes a real look, but a couple of cursory notes:

* The server templates might be better off being built within React. It puts more effort on the client and keeps the systems relevant to the admin in the same ecosystem (React components vs. Nunjucks templates). It also means that we can keep using the bundled CSS file instead of that big style tag. There's a bigger conversation to be had here (you're including stack traces in the templates which is ✨ so there are definitely benefits).
* There are some code-style things that the linter should pick up; it's not part of CI right now, but if you run `npm run lint` it should tell you what I'm talking about.
* To make the whole PR review process a little easier, and for posterity, it'd be great if you could put screenshots of front-end changes in the PR comment. This helps contextualize the changes, and might mean I don't have to pull down your PR and build it, which would save a ton of time.

There's a lot of very different changes in this PR though; do you think you could split it up into multiple PRs? It'll be way easier for me to review the changes and merge them in incrementally. As it is now its kind of an all or nothing situation 🤓

**Comment by etx** [comment]
Yeaahh I should have split these up. My fault! I will do that.

As far as the templates in the backend / react app I think this was is better for a couple of reasons. 
- Easy for the front end devs to override the templates with their own. I guess the server could continue to look for the template file and then redirect to the admin section and it would be the same thing. ¯\_(ツ)_/¯
- It would be weird under any circumstance to direct an end user of the site to a /admin route.
- Loading the entire payload for the admin panel just to show a 404 or template error is unnecessary. The admin comes in at 1.4 megabytes.

**Comment by JasonEtco** [comment]
> Yeaahh I should have split these up. My fault! I will do that.

Thank you <3 I know its some effort to do it now, but it'll be really helpful in the long run

> Easy for the front end devs to override the templates with their own

If its simply reporting error messages, I don't think leaving the templates to userland is a good thing. It opens up the possibility for more errors in those files, which would in turn be hard to debug (because the debugging templates are the ones with bugs). Mental overhead for these error reporting pages should be nil for the dev.

> It would be weird under any circumstance to direct an end user of the site to a /admin route.

Agreed, although I'd prefer to have different behavior in Dev than in Prod for this. End non-admin users should be shown a 404 page for something broken, its better than showing them a stack trace that won't help them. In Dev more useful error pages are super helpful though.

> Loading the entire payload for the admin panel just to show a 404 or template error is unnecessary. The admin comes in at 1.4 megabytes.

I hear you, but I don't think it's a huge problem. The admin bundles are cached, so its basically a guarantee that by the time devs see an error they've downloaded the bundle already. Besides which, with gzip its around 400kb of transfer which isn't too bad.

FWIW, I'm not against keeping it in Nunjucks. After thinking about it some more re: error messages in Dev (or even debug mode), it makes more and more sense since that server-side processing power won't be in production anyway. I would like to find a way to reuse the CSS bundle though, otherwise its a lot of work to keep the styles consistent.

**Comment by etx** [comment]
`npm run lint` isn't giving me out output. Style changes in the react app were minimal and it probably is not looking at the new stuff in the template style tags I added.

**Pull request closed without merging**
